<?php
/**
 * Quick test — send setup guide to email
 * Run once then delete: php /home/u793102776/public_html/cron/send_test.php
 */

$to      = 'javid@iqbalelectronics.com';
$subject = 'IqbalERP - Daily Summary Cron Setup Guide';

$html = '
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;background:#f5f5f5;margin:0;padding:20px;">
<div style="max-width:620px;margin:0 auto;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,0.1);">

    <div style="background:linear-gradient(135deg,#6366f1,#4f46e5);color:#fff;padding:24px 30px;">
        <h1 style="margin:0;font-size:20px;">Daily Summary Cron Job Setup</h1>
        <p style="margin:6px 0 0;opacity:0.9;font-size:14px;">Follow these steps to enable daily email reports</p>
    </div>

    <div style="padding:24px 30px;font-size:14px;line-height:1.7;color:#333;">

        <h2 style="font-size:16px;color:#4f46e5;border-bottom:2px solid #6366f1;padding-bottom:8px;">Step 1: Verify Files</h2>
        <p>Make sure these files exist on your Hostinger server:</p>
        <ul>
            <li><code>/public_html/cron/daily_summary.php</code></li>
            <li><code>/public_html/cron/.htaccess</code></li>
        </ul>
        <p>Check via: <strong>hPanel → File Manager → public_html → cron</strong></p>

        <h2 style="font-size:16px;color:#4f46e5;border-bottom:2px solid #6366f1;padding-bottom:8px;margin-top:24px;">Step 2: Test the Script</h2>
        <p>Go to <strong>hPanel → Advanced → Terminal</strong> and run:</p>
        <div style="background:#1e1e2e;color:#a6e3a1;padding:12px 16px;border-radius:8px;font-family:monospace;font-size:13px;margin:8px 0;">
            php /home/u793102776/public_html/cron/daily_summary.php
        </div>
        <p>You should see: <em>"Summary sent to javid@iqbalelectronics.com"</em></p>
        <p>Check your inbox (and spam folder) for the test email.</p>

        <h2 style="font-size:16px;color:#4f46e5;border-bottom:2px solid #6366f1;padding-bottom:8px;margin-top:24px;">Step 3: Create the Cron Job</h2>
        <p>Go to: <strong>hPanel → Advanced → Cron Jobs</strong></p>
        <table style="width:100%;border-collapse:collapse;margin:12px 0;">
            <tr style="background:#f9fafb;">
                <td style="padding:10px;border:1px solid #e5e7eb;font-weight:600;width:30%;">Command</td>
                <td style="padding:10px;border:1px solid #e5e7eb;">
                    <div style="background:#1e1e2e;color:#a6e3a1;padding:8px 12px;border-radius:6px;font-family:monospace;font-size:12px;">
                        php /home/u793102776/public_html/cron/daily_summary.php
                    </div>
                </td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px solid #e5e7eb;font-weight:600;">Common Setting</td>
                <td style="padding:10px;border:1px solid #e5e7eb;">Once a day</td>
            </tr>
            <tr style="background:#f9fafb;">
                <td style="padding:10px;border:1px solid #e5e7eb;font-weight:600;">Minute</td>
                <td style="padding:10px;border:1px solid #e5e7eb;">0</td>
            </tr>
            <tr>
                <td style="padding:10px;border:1px solid #e5e7eb;font-weight:600;">Hour</td>
                <td style="padding:10px;border:1px solid #e5e7eb;">20 &nbsp;<span style="color:#666;font-size:12px;">(= 11 PM Kuwait time)</span></td>
            </tr>
        </table>
        <p>Click <strong>Create</strong>.</p>

        <h2 style="font-size:16px;color:#4f46e5;border-bottom:2px solid #6366f1;padding-bottom:8px;margin-top:24px;">Step 4: Verify</h2>
        <p>After creating, you will see the cron job listed under <strong>"Current Cron Jobs"</strong>.</p>
        <p>Your first daily summary email will arrive tonight at <strong>11:00 PM Kuwait time</strong>.</p>

        <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px;margin-top:20px;">
            <strong style="color:#15803d;">What the daily email includes:</strong>
            <ul style="margin:8px 0 0;padding-left:20px;color:#166534;">
                <li>Today\'s sales count &amp; total amount</li>
                <li>Sales breakdown by branch/warehouse</li>
                <li>Payments received vs sent</li>
                <li>Total outstanding balance across all invoices</li>
            </ul>
        </div>

    </div>

    <div style="background:#f9fafb;padding:16px 30px;text-align:center;font-size:12px;color:#999;border-top:1px solid #eee;">
        InvenTrack Pro &mdash; Setup guide generated by Claude Code
    </div>
</div>
</body>
</html>
';

$headers  = "MIME-Version: 1.0\r\n";
$headers .= "Content-type: text/html; charset=UTF-8\r\n";
$headers .= "From: InvenTrack Pro <noreply@iqbal.app>\r\n";

if (mail($to, $subject, $html, $headers)) {
    echo "Setup guide sent to {$to}\n";
} else {
    echo "FAILED to send email\n";
}
